# Generated by Django 4.0 on 2021-12-16 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appoinment_date_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appoinment',
            new_name='Appointment',
        ),
    ]
