# Generated by Django 4.0 on 2021-12-16 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_appoinment_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='service',
            new_name='services',
        ),
    ]
