# Generated by Django 4.0 on 2021-12-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_service_appointment_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='decision',
            field=models.CharField(choices=[('PE', 'Pending'), ('AC', 'Accepted'), ('RE', 'Rejected')], default='PE', max_length=2),
        ),
    ]
